### ISSUE TITLE
Build system broken

### ISSUE THREAD

**Issue by LetUsFlow** [Giftzwerg02/tiny-write#1]
I found this repo and immediately wanted to try to use this amazing software.
After cloning the repo I tried to use the following commands to build the software as I am not sure which programming language was used to create tiny-write:
- cargo run
- bun start
- php main.php
- mix run
- go run main.go
- python main.py

But non of these commands worked, they work just fine on my own projects. Is something wrong with my Setup?

I tried both Windows 11 23H2 and Ubuntu 22.04.
Does the CIA spy on my computer and did they stop me from useing this tiny-write?
Is it possible that I was hacked with CSS?

Pls help, I am stuck

**Comment by LetUsFlow** [comment]
As I haven't received an answer yet, I consider this repo to be dead!

**Comment by Giftzwerg02** [comment]
Works on my machine.

**Comment by LetUsFlow** [comment]
Well that doesn't really help me.
Maybe you could try fixing your personal problems?

**Comment by LetUsFlow** [comment]
*personal build problems

**Comment by Giftzwerg02** [comment]
Should be fixed in a76f2a5a5e0505c5ddf0c0966a7e89c9fc689c1e

**Comment by LetUsFlow** [comment]
Oy thank m8
